/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3.Draw;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.*;
import javax.swing.border.Border;


/**
 *
 * @author JotaC
 */
public class Ventana extends javax.swing.JFrame {
    
    JPMap jpanel;
    JProgressBar batteryDrone;
    JProgressBar batteryTotal;
    JLabel coordX,coordY,labelX,labelY;
    JPanel coordPanel;
    /**
     * Creates new form Window
     */
    public Ventana() {
        initComponents();
        jpanel = new JPMap();
        batteryDrone = new JProgressBar();
        batteryTotal = new JProgressBar();
        coordX        = new JLabel();
        coordY        = new JLabel();
        labelX        = new JLabel();
        labelY        = new JLabel();
        coordPanel    = new JPanel();
        
        batteryDrone.setStringPainted(true);
        Border border = BorderFactory.createTitledBorder("Spectro Drone Battery");
        batteryDrone.setBorder(border);
        batteryDrone.setBounds(540, 10, 200, 100);
        
        batteryTotal.setStringPainted(true);
        Border border2 = BorderFactory.createTitledBorder("World's Total Battery");
        batteryTotal.setBorder(border2);
        batteryTotal.setBounds(540, 110, 200, 100);
        
        Border border3 = BorderFactory.createTitledBorder("Current Position");
        coordPanel.setBorder(border3);
        coordPanel.setBounds(540, 220, 150, 50); 
        
        labelX.setText("X: ");
        coordX.setText("0");
        labelY.setText("Y: ");
        coordY.setText("0");
        
        coordPanel.add(labelX);
        coordPanel.add(coordX);
        coordPanel.add(labelY);
        coordPanel.add(coordY);
        
        this.add(jpanel);
        this.add(batteryDrone);
        this.add(batteryTotal);
        this.add(coordPanel);
        this.setTitle("Ventana");  
    }
    
    public JPMap getJpanel(){
        return jpanel; 
    }
    
    public void setBatteryDroneValue(int value){
        batteryDrone.setValue(value);
        batteryDrone.repaint();
    }
    
    public void setTotalBatteryValue(int value){
        Double d = value*0.1;
        batteryTotal.setValue(d.intValue());
        batteryTotal.repaint();
    }
    
    public void setLabelCoordinate(int x,int y){
        
        String cX = Integer.toString(x);
        String cY = Integer.toString(y);
        
        coordX.setText("["+cX+"]");
        coordX.repaint();
        coordY.setText("["+cY+"]");
        coordY.repaint();
        //coordPanel.repaint();                  
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
