package practica3.Draw;

import javax.swing.*;
import javax.swing.border.Border;

/**
 * Window
 *
 * @author José Carlos Alfaro
 */
public class Window extends javax.swing.JFrame {

    JPMap jpanel;
    JProgressBar batteryDrone;
    JProgressBar batteryTotal;
    JLabel coordX, coordY, labelX, labelY;
    JPanel coordPanel;

    /**
     * Constructor
     * 
     * @author José Carlos Alfaro
     */
    public Window() {
        initComponents();
        this.jpanel = new JPMap();
        this.batteryDrone = new JProgressBar();
        this.batteryTotal = new JProgressBar();
        this.coordX = new JLabel();
        this.coordY = new JLabel();
        this.labelX = new JLabel();
        this.labelY = new JLabel();
        this.coordPanel = new JPanel();

        this.batteryDrone.setStringPainted(true);
        Border border = BorderFactory.createTitledBorder("Spectro Drone Battery");
        this.batteryDrone.setBorder(border);
        this.batteryDrone.setBounds(540, 10, 200, 100);

        this.batteryTotal.setStringPainted(true);
        Border border2 = BorderFactory.createTitledBorder("World's Total Battery");
        this.batteryTotal.setBorder(border2);
        this.batteryTotal.setBounds(540, 110, 200, 100);

        Border border3 = BorderFactory.createTitledBorder("Current Position");
        this.coordPanel.setBorder(border3);
        this.coordPanel.setBounds(540, 220, 150, 50);

        this.labelX.setText("X: ");
        this.coordX.setText("0");
        this.labelY.setText("Y: ");
        this.coordY.setText("0");

        this.coordPanel.add(labelX);
        this.coordPanel.add(coordX);
        this.coordPanel.add(labelY);
        this.coordPanel.add(coordY);

        this.add(this.jpanel);
        this.add(this.batteryDrone);
        this.add(this.batteryTotal);
        this.add(this.coordPanel);
        this.setTitle("Realtime observation");
    }

    /**
     * Return panel to draw the map in
     * 
     * @return Drawing area
     * @author José Carlos Alfaro
     */
    public JPMap getJpanel() {
        return this.jpanel;
    }

    /**
     * Set new battery value of drone
     * 
     * @param value New battery value of drone
     * @author José Carlos Alfaro
     */
    public void setBatteryDroneValue(int value) {
        this.batteryDrone.setValue(value);
        this.batteryDrone.repaint();
    }

    /**
     * Set new total battery value
     * 
     * @param value New total battery value
     * @author José Carlos Alfaro
     */
    public void setTotalBatteryValue(int value) {
        Double d = value * 0.1;
        this.batteryTotal.setValue(d.intValue());
        this.batteryTotal.repaint();
    }

    /**
     * Set new coordinates
     * 
     * @param x x coordinate
     * @param y y coordinate
     * @author José Carlos Alfaro
     */
    public void setLabelCoordinate(int x, int y) {
        String cX = Integer.toString(x);
        String cY = Integer.toString(y);

        this.coordX.setText("[" + cX + "]");
        this.coordX.repaint();
        this.coordY.setText("[" + cY + "]");
        this.coordY.repaint();               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
